### ISSUE TITLE
NullPointerException when referencing to Feather instance

### ISSUE THREAD

**Issue by ZeroMemes** [KNOXDEV/feather#2]
Any reference to the **Feather Instance** will result in a ``NullPointerException``. This is caused by the creation of a ``Tessellator`` object on the instance's initialization which then refers back to the not fully initialized instance. *(Refer to ``BasicTess`` constructor)*. This can be solved by making ``Feather#tess`` static.

**Comment by KNOXDEV** [comment]
Sorry about that, I forgot to commit the fix. Thanks!
b7f3c7bff0997e36326d1882416f36cfd61c83fa
