### ISSUE TITLE
Add a build file for JitPack support

### ISSUE THREAD

**Issue by LeafHacker** [KNOXDEV/feather#7]
JitPack [requires](https://jitpack.io/docs/BUILDING/) libraries to have a working build file in their repo, in order to automatically include the lib in their maven.

Adding your build files would enable projects to easily depend on feather without having to clone and build it or include its code in their own repo.

**Comment by ZeroMemes** [comment]
Relevant Pull Requests: #9 #10

**Comment by LeafHacker** [comment]
[Fixed](https://jitpack.io/#KNOXDEV/feather). Thanks @ZeroMemes
